### ISSUE TITLE
Some GCC warnings

### ISSUE THREAD

**Issue by SteveRussell33** [anlexmatos/MIDI-Delexander#2]
g++ -std=c++11 -Wsuggest-override  -fPIC -I../../include -I../../dep/include -MMD -MP -g -O3 -march=nocona -funsafe-math-optimizations -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -c -o build/src/SuperMIDI64.cpp.o src/SuperMIDI64.cpp
src/SuperMIDI64.cpp: In member function 'void SuperMIDI64::releaseNote(uint8_t, uint8_t, uint8_t)':
src/SuperMIDI64.cpp:644:8: warning: variable 'backnote' set but not used [-Wunused-but-set-variable]
  644 |   bool backnote = false;
      |        ^~~~~~~~
src/SuperMIDI64.cpp: In member function 'virtual void PolyModeDisplayC::draw(const rack::widget::Widget::DrawArgs&)':
src/SuperMIDI64.cpp:1327:27: warning: comparison is always false due to limited range of data type [-Wtype-limits]
 1327 |      if ((lrnflash += 16) > 255) lrnflash = 0;
      |          ~~~~~~~~~~~~~~~~~^~~~~
src/SuperMIDI64.cpp:1340:27: warning: comparison is always false due to limited range of data type [-Wtype-limits]
 1340 |      if ((lrnflash += 16) > 255) lrnflash = 0;
      |          ~~~~~~~~~~~~~~~~~^~~~~
src/SuperMIDI64.cpp:1353:27: warning: comparison is always false due to limited range of data type [-Wtype-limits]
 1353 |      if ((lrnflash += 16) > 255) lrnflash = 0;
      |          ~~~~~~~~~~~~~~~~~^~~~~
src/SuperMIDI64.cpp:1366:27: warning: comparison is always false due to limited range of data type [-Wtype-limits]
 1366 |      if ((lrnflash += 16) > 255) lrnflash = 0;

**Comment by xandramax** [comment]
Thanks for the reminder; I'd been ignoring these as they are present in the original moDllz MIDIpolyMPE code and they didn't seem to be causing any problems.

I'm not certain what the four lrnflash lines were intended to do, but the associated selectors (note range and velocity range) seem to work just fine without them.

As for the boolean "backnote", it seems to have only been intended for use in MPE+ mode (specifically when releasing a note), though it was only set there and never read. I don't yet have a MPE+ controller to experiment with in order to see if there is any problem there, but I'm waiting on an Osmose delivery hopefully this summer so I should be able to dig in to this part of the code more at that point.

For now I've commented these lines out in order to get rid of the warnings, and I'll wait to see if any issues are later apparent with the Note and Velocity Range selectors or note release in MPE+.
